import { DatePicker, Space } from "antd";
import Image from "next/image";

import second1 from "../../../public/assets/CoverPhoto/images1.jpg";

export const metadata = {
  title: "About Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="text-center p-12">
      <div className="text-center items-center pb-5">
        <h2 className="text-2xl text-center">This is about Page</h2>
        <div className="flex w-full flex-col gap-4">
          <div className="skeleton h-32 w-full">1</div>
          <div className="skeleton h-4 w-full">2</div>
          <div className="skeleton h-4 w-full">3</div>
          <div className="skeleton h-4 w-full">4</div>
        </div>
      </div>

      <Space direction="vertical">
        <DatePicker />
      </Space>
    </div>
  );
};

export default AboutPage;
